using ADigitalCompany.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace ADigitalCompany.Persistence.Configurations
{
    public class DepartmentConfiguration : IEntityTypeConfiguration<Department>
    {
        public void Configure(EntityTypeBuilder<Department> builder)
        {
            builder.ToTable("Departments");

            builder.HasKey(x => x.Id);

            builder.Property(x => x.Name)
                .IsRequired()
                .HasMaxLength(100);

            builder.Property(x => x.Code)
                .IsRequired() //Maybe autogenerated
                .HasMaxLength(20);

            builder.HasIndex(x => x.Code)
                .IsUnique();

            builder.Property(x => x.Description)
                .HasMaxLength(300);

            builder.Property(x => x.Location)
                .HasMaxLength(150);

            builder.Property(x => x.ResponsibleId)
                .HasMaxLength(450);

            builder.HasData(
                new
                {
                    Id = 1,
                    Name = "Administration",
                    Code = "ADM",
                    Description = "Administration Department",
                    Location = "Building A",
                    ResponsibleId = "8e445865-a24d-4543-a6c6-9443d048cdb9"
                },
                new
                {
                    Id = 2,
                    Name = "Production",
                    Code = "PROD",
                    Description = "Production Department",
                    Location = "Plant 1",
                    ResponsibleId = "9e224968-33e4-4652-b7b7-8574d048cdb9"
                }
            );
        }
    }
}